version: '2.2'
services:
  local-mysql:
    image: mysql:5.7
    container_name: local-mysql
    cpus: 2
    mem_limit: 2048m
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --connect-timeout=60
      - --max-connections=11000
      - --max-allowed-packet=32M
      - --thread-cache-size=300
      - --sort-buffer-size=4M
      - --bulk-insert-buffer-size=16M
      - --tmp-table-size=256M
      - --max-heap-table-size=2048M
      - --query-cache-limit=4M
      - --query-cache-size=64M
      - --query-cache-type=0
      - --long-query-time=10
      - --expire-logs-days=10
      - --max-binlog-size=100M
      - --innodb-buffer-pool-size=256M
      - --innodb-log-buffer-size=32M
      - --innodb-file-per-table=1
      - --innodb-open-files=400
      - --innodb-io-capacity=400
      - --innodb-flush-method=O_DIRECT
      - --sql-mode=STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    networks:
      - local-network
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d/
      - mysql-volume:/var/lib/mysql

  local-redis:
    image: redis:7.2.3
    container_name: local-redis
    cpus: 2
    mem_limit: 768m
    networks:
      - local-network
    ports:
      - 6379:6379
    volumes:
      - redis-volume:/data
  localstack:
    image: localstack/localstack
    container_name: "localstack"
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=${SERVICES-sqs,sns}
      - DEBUG=${DEBUG- }
      - START_WEB=1
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_SECRET_ACCESS_KEY=qualquercoisa
      - AWS_ACCESS_KEY_ID=qualquercoisa
      - HOSTNAME=localstack
    networks:
      - local-network
    volumes:
      - localstack-volume:/var/lib/localstack
      - ./docker/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  local-network:
    name: local-network
    external: true

volumes:
  mysql-volume: {}
  redis-volume: {}
  localstack-volume: {}